const universal=[
 {title:'Seu primeiro projeto',text:'Você quer mostrar que está aprendendo. Qual é o melhor próximo passo?',options:['Copiar um projeto e dizer que fez sozinho','Construir algo simples, explicar suas escolhas e publicar','Esperar saber tudo antes de começar','Comprar o computador mais caro'],answer:1,why:'Um projeto pequeno e bem explicado mostra prática, iniciativa e aprendizado.'},
 {title:'Missão em equipe',text:'Você travou em um problema e o prazo está chegando. O que faz?',options:['Esconde o problema até o último minuto','Culpa outra pessoa','Explica o que tentou e pede ajuda com antecedência','Apaga tudo e começa sem avisar'],answer:2,why:'Comunicar dificuldades e pedir ajuda com contexto faz parte do trabalho em TI.'},
 {title:'Mensagem suspeita',text:'Chegou uma mensagem pedindo sua senha para liberar uma vaga. Qual a sua reação?',options:['Envio a senha porque a vaga parece boa','Confiro a origem por um canal oficial e não envio a senha','Encaminho para todos os colegas','Clico primeiro para ver o que acontece'],answer:1,why:'Senhas não devem ser compartilhadas. Verifique mensagens e oportunidades pelos canais oficiais.'},
 {title:'Chefe final: entrevista',text:'Perguntaram sobre uma ferramenta que você ainda não conhece. Como responde?',options:['Invento que já trabalhei com ela','Digo que não conheço, conecto ao que sei e explico como aprenderia','Falo que aprender é responsabilidade da empresa','Encerro a entrevista'],answer:1,why:'Honestidade, raciocínio e disposição para aprender contam. O jogo é uma simulação, não uma garantia de contratação.'}
];
const specific={
 dev:{title:'Bug na missão',text:'Seu site ficou estranho depois de uma alteração. O que faz primeiro?',options:['Apaga o projeto inteiro','Compara a alteração, reproduz o erro e verifica o console','Compra outro notebook','Finge que é uma nova funcionalidade'],answer:1,why:'Reproduzir o erro e investigar a mudança ajuda a encontrar a causa.'},
 suporte:{title:'O PC não liga!',text:'Um colega diz que o computador não liga. Qual é o primeiro passo?',options:['Formatar o computador','Verificar tomada, cabos e alimentação','Trocar o monitor imediatamente','Dizer: ontem estava funcionando!'],answer:1,why:'Comece pelas verificações básicas antes de partir para soluções mais complexas.'},
 infra:{title:'Cadê a conexão?',text:'Só um computador da sala está sem internet. Por onde começar?',options:['Reiniciar a rede inteira','Verificar a conexão desse computador e comparar com outro','Apagar os arquivos','Trocar todos os computadores'],answer:1,why:'Compare o dispositivo afetado com um que funciona e investigue a conexão local.'},
 cyber:{title:'Escudo digital',text:'Você precisa proteger uma conta. Qual combinação ajuda mais?',options:['Senha igual em todos os sites','Senha única e forte com autenticação em dois fatores','Data de aniversário como senha','Compartilhar a senha com um amigo'],answer:1,why:'Uma senha exclusiva e um segundo fator reduzem o risco de acesso indevido.'}
};
function questions(p){return [specific[p.area],...universal]}

module.exports={specific,questions};
