const crypto=require('node:crypto'),QR=require('qrcode');
const {specific,questions}=require('../lib/game-data');
function publicRoom(r){return {code:r.code,status:r.status,open:r.open,joinUrl:r.joinUrl,players:Object.values(r.players).map(p=>({id:p.id,name:p.name,area:p.area,avatar:p.avatar,xp:p.xp,stage:p.stage,finished:p.stage===5})).sort((a,b)=>b.xp-a.xp||b.stage-a.stage||a.name.localeCompare(b.name))}}
class HttpError extends Error{constructor(message,status=400){super(message);this.status=status}}
function redisConfig(){
// A integração Upstash da Vercel fornece os aliases KV_* como segredos gerenciados.
if(process.env.UPSTASH_REDIS_REST_URL&&process.env.UPSTASH_REDIS_REST_TOKEN)return {url:process.env.UPSTASH_REDIS_REST_URL,token:process.env.UPSTASH_REDIS_REST_TOKEN};
if(process.env.KV_REST_API_URL&&process.env.KV_REST_API_TOKEN)return {url:process.env.KV_REST_API_URL,token:process.env.KV_REST_API_TOKEN};
throw new HttpError('O banco online ainda não foi configurado pelo apresentador.',503)
}
async function redis(command){const config=redisConfig();const r=await fetch(config.url,{method:'POST',headers:{Authorization:'Bearer '+config.token,'Content-Type':'application/json'},body:JSON.stringify(command),signal:AbortSignal.timeout(8000)});const j=await r.json();if(!r.ok||j.error)throw new HttpError('O banco está temporariamente indisponível. Tente novamente.',503);return j.result}
const prefix='missao-ti:room:';
async function get(code){if(!/^\d{6}$/.test(String(code)))throw new HttpError('Informe um código de sala válido.',404);const raw=await redis(['GET',prefix+code]);if(!raw)throw new HttpError('Sala não encontrada. Escaneie o QR Code atual.',404);return {raw,room:JSON.parse(raw)}}
const CAS="if redis.call('GET',KEYS[1]) == ARGV[1] then redis.call('SET',KEYS[1],ARGV[2],'EX',ARGV[3]); return 1 else return 0 end";
async function mutate(code,fn){for(let i=0;i<8;i++){const {raw,room}=await get(code);const result=fn(room);const ok=await redis(['EVAL',CAS,1,prefix+code,raw,JSON.stringify(room),86400]);if(ok===1)return result}throw new HttpError('Muitos jogadores responderam juntos. Tente novamente.',409)}
function me(r,token){const p=Object.values(r.players).find(p=>p.token===token);if(!p)throw new HttpError('Sua entrada não foi encontrada. Entre novamente.',403);return p}
function admin(r,token){if(r.token!==token)throw new HttpError('Controle não autorizado.',403)}
function origin(req){const base=process.env.PUBLIC_BASE_URL;if(base){const u=new URL(base);if(u.protocol!=='https:')throw new HttpError('O endereço público precisa usar HTTPS.',503);return u.origin}const host=req.headers.host;if(!host||!host.endsWith('.vercel.app'))throw new HttpError('Configure PUBLIC_BASE_URL com o domínio público do jogo.',503);return 'https://'+host}
async function handle(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');try{const u=new URL(req.url,'https://localhost');const action=u.searchParams.get('action')||u.pathname.split('/').pop();const b=req.method==='POST'?(typeof req.body==='string'?JSON.parse(req.body):req.body||{}):{};const code=b.code||u.searchParams.get('sala');const token=b.token||u.searchParams.get('token');
if(action==='qr'){const url=u.searchParams.get('url');if(!url||url.length>500)throw new HttpError('Endereço inválido.');res.setHeader('Content-Type','image/svg+xml');return res.end(await QR.toString(url,{type:'svg',margin:2,width:340,errorCorrectionLevel:'M'}))}
if(['create','join','control','answer'].includes(action)&&req.method!=='POST')throw new HttpError('Método não permitido.',405);
if(action==='create'){const token=crypto.randomBytes(24).toString('hex');for(let i=0;i<8;i++){const code=crypto.randomInt(100000,1000000).toString();const r={code,token,status:'playing',open:true,players:{},joinUrl:origin(req)+'/jogar?sala='+code};if(await redis(['SET',prefix+code,JSON.stringify(r),'NX','EX',86400]))return res.json({...publicRoom(r),token})}throw new HttpError('Tente criar a sala novamente.',409)}
if(action==='state')return res.json(publicRoom((await get(code)).room));
if(action==='join'){const name=String(b.name||'').trim().replace(/[<>]/g,'').slice(0,20);if(name.length<2)throw new HttpError('Use um apelido com pelo menos 2 letras.');if(!specific[b.area])throw new HttpError('Escolha sua área.');const id=crypto.randomUUID(),pt=crypto.randomBytes(24).toString('hex');return res.json(await mutate(code,r=>{if(!r.open||r.status==='ended')throw new HttpError('As inscrições foram encerradas.');if(Object.keys(r.players).length>=150)throw new HttpError('A sala atingiu 150 jogadores.');if(Object.values(r.players).some(p=>p.name.toLowerCase()===name.toLowerCase()))throw new HttpError('Este apelido já está em uso.');r.players[id]={id,token:pt,name,area:b.area,avatar:Math.min(7,Math.max(0,Number(b.avatar)||0)),xp:0,stage:0,last:null};return {id,token:pt,code:r.code}}))}
if(action==='control')return res.json(await mutate(code,r=>{admin(r,token);if(b.command==='toggle')r.open=!r.open;else if(b.command==='end')r.status='ended';else throw new HttpError('Comando inválido.');return publicRoom(r)}));
if(action==='me'){const r=(await get(code)).room,p=me(r,token),q=r.status==='playing'&&p.stage<5?questions(p)[p.stage]:null;return res.json({status:r.status,player:{name:p.name,area:p.area,avatar:p.avatar,xp:p.xp,stage:p.stage},question:q?{title:q.title,text:q.text,options:q.options}:null})}
if(action==='answer')return res.json(await mutate(code,r=>{const p=me(r,token);if(b.stage===p.stage-1&&p.last)return p.last;if(r.status!=='playing'||p.stage>=5)throw new HttpError('Esta partida não está recebendo respostas.');if(b.stage!==p.stage||!Number.isInteger(b.choice)||b.choice<0||b.choice>3)throw new HttpError('Resposta inválida.');const q=questions(p)[p.stage],correct=b.choice===q.answer;p.xp+=correct?200:50;p.stage++;return p.last={correct,gain:correct?200:50,why:q.why,xp:p.xp,stage:p.stage}}));
throw new HttpError('Ação inválida.',404)
}catch(e){res.status(e.status||500).json({error:e.status?e.message:'Não foi possível concluir. Tente novamente.'})}}
module.exports=handle;
